### ISSUE TITLE
Got to ask: How do you plan on tackling day 7 part 2?

### ISSUE THREAD

**Issue by Vaelatern** [sdiepend/advent_of_code-pharo#1]
I've been having issues making my VMs concurrent. I don't want to just manually tick VMs...

**Comment by sdiepend** [comment]
@Vaelatern, good question, I'm still learning Pharo.I haven't got time to do part 2 yet, if I don't find it I'll probably have to ask my colleagues who are more versed in Pharo/SmallTalk.

**Comment by Vaelatern** [comment]
I'm learning it too, using `[] fork` to keep VMs running independently, but it doesn't seem to be quite enough.

**Comment by Vaelatern** [comment]
I worked out a way that works! For me at least, it works quite well. It involves forking off the first 4 interpreters but after linking them with `AtomicSharedQueue`s as my input and output streams.
